# Generated by Django 4.1 on 2022-11-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='game',
        ),
        migrations.RemoveField(
            model_name='action',
            name='player',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='club',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_played',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(1, 'not-started'), (2, 'playing'), (3, 'played')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(1, 'GK'), (2, 'RB'), (3, 'CB'), (4, 'LB'), (5, 'CMD'), (6, 'MD'), (7, 'RW'), (8, 'LW'), (9, 'ST'), (10, 'trainer'), (11, 'sub-trainer'), (12, 'analytic')]),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
