# Generated by Django 4.1 on 2022-11-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_action_game_remove_action_player_delete_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passes',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passes',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.game'),
            preserve_default=False,
        ),
    ]
