# Generated by Django 4.1 on 2022-11-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substitute',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_on', to='main.player'),
        ),
    ]
