# Generated by Django 4.1 on 2022-11-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_substitute_game_alter_substitute_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='is_img',
            field=models.BooleanField(default=False),
        ),
    ]
