# Generated by Django 4.1 on 2022-11-30 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_detail_img_alter_detail_is_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='telegram',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='status',
        ),
        migrations.AddField(
            model_name='detail',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passes',
            name='name',
            field=models.CharField(default=1, max_length=210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detail'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
