# Generated by Django 4.1 on 2022-11-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_chat_id_chat_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.club'),
            preserve_default=False,
        ),
    ]
