# Generated by Django 4.1 on 2022-12-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_image_alter_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passes',
            name='club',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='game',
        ),
        migrations.AddField(
            model_name='passes',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.player'),
            preserve_default=False,
        ),
    ]
