# Generated by Django 4.1 on 2022-12-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_passes_club_remove_passes_game_passes_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sub_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sub_on',
            field=models.IntegerField(default=0),
        ),
    ]
