# Generated by Django 4.1 on 2022-12-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_player_sub_off_player_sub_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passes',
            old_name='all',
            new_name='smth',
        ),
    ]
