# Generated by Django 4.1 on 2022-12-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_all_passes_smth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passes',
            old_name='smth',
            new_name='all',
        ),
    ]
