from django.urls import path
from .views import *

urlpatterns = [
    path('register/', register),
    path('login/', login_api),
    path('logout/', logout_api),
    path('get-user/', user_api),
    path('get-info/', info_api),
    path('get-ads/', ads_api),
    path('get-slider/', slider_api),
    path('get-report/', report_api),
    path('get-video/', video_api),
    path('get-news/', news_api),
    path('get-league/', league_api),
    path('get-club/', club_api),
    path('get-player/', player_api),
    path('get-staff/', staff_api),
    path('get-game/', game_api),
    path('get-subs/', subs_api),
    path('get-line/', line_api),
    path('get-goal/', goal_api),
    path('get-passes/', passes_api),
    path('get-statics/', statics_api),
    path('get-table/', table_api),
    path('get-detail/', detail_api),
    path('get-product/', product_api),
    path('get-wishlist/', wishlist_api),
    path('get-order-item/', order_item_api),
    path('get-order/', order_api),
    path('get-chat/', chat_api),
    path('get-telegram/', telegram_api),
    path('single-user/<int:pk>/', single_user),
    path('single-report/<int:pk>/', single_report),
    path('single-video/<int:pk>/', single_video),
    path('single-news/<int:pk>/', single_news),
    path('single-table/<int:pk>/', single_table),
    path('single-player/<int:pk>/', single_player),
    path('single-game/<int:pk>/', single_game),
    path('single-product/<int:pk>/', single_product),
    path('add-wishlist/', add_wishlist),
    path('add-order-item/', add_order_item),
    path('add-order/', add_order),
]
